# PyRadiomics v3.1.0

imageType:
    Original: {}

featureClass:
    shape: []
    firstorder: []

setting:
    # Image discretization:
    binWidth: 25

    # first order specific settings:
    voxelArrayShift: 1000  # Minimum value in HU is -1000, shift +1000 to prevent negative values from being squared.

    label: 1
